### ISSUE TITLE
The Project doesn't build in Xcode 12 with Swift 5.3.

### ISSUE THREAD

**Issue by shyamalschandra** [webex/webex-ios-sdk-example#23] opened 2020-10-10 12:41 UTC
The instructions on the github are incomplete and the resulting xcworkspace file doesn't build properly with many errors. Could you please rectify the situation?

I am getting the following errors when I follow the step-by-step (incomplete) instructions on the Cisco website:

<img width="787" alt="Screen Shot 2020-10-10 at 7 40 07 AM" src="https://user-images.githubusercontent.com/9545735/95655302-e1ed5b80-0acb-11eb-898f-e71279d90084.png">

**Comment by judupree** [comment] 2020-10-12 01:02
Hello - this appears to be a duplicate of issue https://github.com/webex/webex-ios-sdk/issues/64 - most recent comment there was the following by @MrShiY 

@shyamalschandra have you resolved this issue? I have two solutions to reference.

try pod update, if not work, please delete 'Podfile.lock', then pod update.
Alternative, change the Build Settings -> iOS Deployment Target of the error dependencies as iOS 9.0.

**Comment by shyamalschandra** [comment] 2020-10-12 14:03
Hi, it seems like a duplicate but it is a totally different issue for a different repository with different files.  Please update the files and test for XCode 12 and iOS 14.  Thanks!

**Comment by MrShiY** [comment] 2020-12-17 09:20
@shyamalschandra Just released a new version 2.7.0,  Can you have a try again?

**Comment by MrShiY** [comment] 2021-03-02 07:07
no reply for a long time

**Closed by MrShiY** 2021-03-02 07:07 UTC
